#pragma once
#include <algorithm>
#include <cassert>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>
#include "cudd.h"
#include "util.h"
#include "Context.hpp"
#include "Parser.hpp"
#include "Solver.hpp"